### ISSUE TITLE
✨ Feat (UI): Implement Granular Consent UI for GDPR Compliance 🍪

### ISSUE THREAD

**Issue by chriskyfung** [chriskyfung/amp-affiliately-jekyll-theme#44]
**Title:** Implement Granular Consent UI for GDPR Compliance

## Description

The current AMP-ready Jekyll theme includes services that utilize cookies to store user data. To ensure compliance with the General Data Protection Regulation (GDPR), we need to implement a granular consent UI that allows users to control their cookies on a per-purpose basis.

## Problem

The theme does not currently provide users with a way to opt in or out of specific cookie purposes, which could result in non-compliance with GDPR requirements.

## Proposed Solution

We propose implementing a Consent UI that includes the following features:

- [x] **Granular Consent:** Users should be able to consent to or reject individual cookie purposes separately.
- [ ] **Clear and Transparent Information:** Users should be provided with clear and concise information about each cookie purpose before giving their consent.
- [ ] **Easy to Access:** The Consent UI should be easily accessible and visible to users.
- [ ] **AMP Compatibility:** The Consent UI must be implemented in a way that maintains AMP validity.

## Possible Implementations

One possible implementation could involve using a third-party consent management platform (CMP) that is AMP-compatible. CMPs provide a range of features out-of-the-box, including granular consent options, data collection, and reporting.

Another approach could be to develop a custom Consent UI using AMP elements. This would require more development effort but could provide greater control over the UI's design and functionality.

## Benefits

Implementing a granular Consent UI will provide the following benefits:

* **GDPR Compliance:** Ensure that the theme complies with GDPR requirements for cookie consent.
* **User Privacy Protection:** Give users control over their personal data and how it is used.
* **Improved User Experience:** Empower users to make informed decisions about their cookie preferences.

## Timeline

This feature should be prioritized and completed within the next sprint.

## Assignee

To be assigned after discussion and review of proposed implementations.

## Additional Notes

* We should consider using a CMP that is lightweight and does not impact page performance.
* The Consent UI should be designed to be user-friendly and easy to understand.
* We should provide documentation and guidance to users on how to use the Consent UI.

### Objectives

* Create a user-friendly and compliant Consent UI using AMP elements.
* Ensure compliance with industry regulations and best practices.
* Provide a seamless and transparent user experience.

### Tasks

**Phase 1: Design and Development**

- [ ] Design the Consent UI using AMP elements, considering accessibility and responsiveness.
- [x] Develop the UI using AMP's HTML and JavaScript components.
- [x] Implement the necessary AMP state management and event handling.
- [x] Ensure the UI is visually appealing and aligns with the brand guidelines.

**Phase 2: Integration and Testing**

- [x] Integrate the Consent UI into the existing website or application.
- [ ] Conduct thorough testing to verify functionality, performance, and accessibility.
- [ ] Perform user acceptance testing to gather feedback and validate the UI.

**Phase 3: Deployment and Maintenance**

- [x] Deploy the Consent UI on the production site.
- [ ] Monitor the UI's performance and address any issues promptly.
- [ ] Regularly update the UI to maintain compliance and enhance user experience.

### Additional Tasks

- [ ] **Legal Compliance:** Review and align the Consent UI with applicable laws and regulations.
- [ ] **Transparency:** Provide clear and concise information to users about the purpose and use of their data.
- [x] **Granularity:** Allow users to specify granular consent preferences for different purposes and vendors.
- [x] **Revocability:** Enable users to easily revoke their consent at any time.
- [ ] **Accessibility:** Ensure the Consent UI is accessible to users with disabilities.
- [ ] **Vendor Management:** Integrate with vendor consent management platforms to streamline consent collection and management.

**Comment by chriskyfung** [comment]
To collect cookie consent on AMP pages, you need to use the `<amp-consent>` element and the `data-block-on-consent` or `data-block-on-consent-purposes` attribute. Here's a step-by-step guide on how to set it up:

1. **Add the `<amp-consent>` element** to your AMP pages.
2. **Use the `data-block-on-consent` attribute** to block all elements that require consent, or use the `data-block-on-consent-purposes` attribute with a comma-separated list of consent purposes to set the categories to be prioritized.
3. **To retrieve the consent string on AMP**, third-party vendors can use `context.initialConsentValue`.
4. **Since AMP does not allow the loading of iframes from the same domain**, uploading the cookie notice file on the same domain as your AMP page will result in the cookie notice not being displayed. Therefore, host the HTML file on a different domain or subdomain (e.g., main domain is `www.yourdomain.com`, but you host the file on `amp.yourdomain.com`). This approach also works if you redirect from a subdomain to your main domain.
5. **The `<amp-consent>` element needs to be served via HTTPS**.

For a step-by-step guide (complete with sample codes, a demo, and WordPress tips) and more information on how to block cookies before user consent on Accelerated Mobile Pages, read the guide on integrating iubenda Privacy Controls and Cookie Solution with AMP[1].

Citations:
[1] https://www.iubenda.com/en/help/3182-cookie-consent-amp-pages
[2] https://amp.dev/documentation/components/amp-consent
[3] https://onetrustprivacy.my.site.com/cpcustomers/s/article/UUID-94cf9b13-1998-d989-a5e0-d01a73a2e0a7?language=en_US
[4] https://wordpress.org/support/topic/google-amp-compatibility-5/
[5] https://www.iubenda.com/en/help/22135-cookie-solution-amp-wordpress

**Comment by chriskyfung** [comment]
- [[amp-consent] Fine grain, client-side consent · Issue #26735 · ampproject/amphtml](https://github.com/ampproject/amphtml/issues/26735)
- [amp-consent: let developers show existing consent choices on reprompt · Issue #33530 · ampproject/amphtml](https://github.com/ampproject/amphtml/issues/33530)
- [Update Consent is not working in Granular Consent · Issue #34517 · ampproject/amphtml](https://github.com/ampproject/amphtml/issues/34517)

**Comment by chriskyfung** [comment]
## ConsentManager CMP

To configure `amp-consent` with ConsentManager CMP, follow these steps:

### Step-by-Step Configuration

1. **Add AMP Consent Script**:
   Include the `amp-consent` script in the `<head>` section of your AMP page:
   ```html
   <script async custom-element="amp-consent" src="https://cdn.ampproject.org/v0/amp-consent-0.1.js"></script>
   ```

2. **Add Meta Tag for Consent Blocking**:
   Add a meta tag to specify which AMP components should be blocked until consent is given:
   ```html
   <meta name="amp-consent-blocking" content="amp-ad">
   ```

3. **Configure Consent Layer**:
   Add the `amp-consent` element to the `<body>` section of your AMP page. Use the configuration provided by ConsentManager CMP:
   ```html
   <amp-consent id="ConsentManager" layout="nodisplay" type="ConsentManager">
     <script type="application/json">
       {
         "postPromptUI": "postPromptUI",
         "clientConfig": {
           "cdid": "Your CMP Code-ID",
           "params": ""
         }
       }
     </script>
     <div id="postPromptUI">
       <button on="tap:ConsentManager.prompt()" role="button">Manage privacy settings</button>
     </div>
   </amp-consent>
   ```

4. **Blocking Ads and Analytics**:
   To block ads or analytics codes until consent is given, add the `data-block-on-consent` attribute to the relevant AMP elements:
   ```html
   <amp-ad data-block-on-consent type="doubleclick" width="300" height="250" layout="responsive"></amp-ad>
   <amp-analytics data-block-on-consent type="googleanalytics"></amp-analytics>
   ```

### Example Configuration

Here's a complete example of how your AMP page might look with the `amp-consent` and ConsentManager CMP integration:

```html
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>AMP Consent Example</title>
  <link rel="canonical" href="self.html">
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-consent" src="https://cdn.ampproject.org/v0/amp-consent-0.1.js"></script>
  <meta name="amp-consent-blocking" content="amp-ad">
</head>
<body>
  <amp-consent id="ConsentManager" layout="nodisplay" type="ConsentManager">
    <script type="application/json">
      {
        "postPromptUI": "postPromptUI",
        "clientConfig": {
          "cdid": "Your CMP Code-ID",
          "params": ""
        }
      }
    </script>
    <div id="postPromptUI">
      <button on="tap:ConsentManager.prompt()" role="button">Manage privacy settings</button>
    </div>
  </amp-consent>

  <amp-ad data-block-on-consent type="doubleclick" width="300" height="250" layout="responsive"></amp-ad>
  <amp-analytics data-block-on-consent type="googleanalytics"></amp-analytics>
</body>
</html>
```

For more detailed instructions and examples, you can refer to the [AMP example](https://github.com/ampproject/amphtml/blob/main/extensions/amp-consent/cmps/consentmanager.md) [ConsentManager documentation](https://help.consentmanager.net/books/cmp/page/using-the-cmp-with-amp-websites). This should help you get started with integrating ConsentManager CMP on your AMP pages.

**Comment by chriskyfung** [comment]
## Ensuring Compliance with `data-npa-on-unknown-consent`

The `data-npa-on-unknown-consent` attribute is used in AMP pages to handle situations where the user's consent status is unknown. This attribute ensures that non-personalized ads (NPAs) are served when the user's consent status is not explicitly known. This is particularly important for complying with privacy regulations and maintaining ad revenue. Here's how it works and when you might need to include it:

### Purpose and Usage

1. **Non-Personalized Ads (NPAs)**: NPAs are ads that are not based on a user's past behavior. Instead, they use contextual information, such as the content of the current site or app, and coarse geo-targeting (e.g., city-level) based on the user's current location. NPAs do not use cookies or mobile ad identifiers for ad targeting, but they may still use them for frequency capping and aggregated ad reporting.

2. **Handling Unknown Consent Status**: When the user's consent status is unknown (e.g., if the user dismisses the consent prompt), the `data-npa-on-unknown-consent` attribute ensures that NPAs are served instead of personalized ads. This helps in complying with privacy regulations that require non-personalized ads to be served when user consent is not explicitly given.

3. **Regulatory Compliance**: This attribute is essential for complying with privacy regulations such as the GDPR and CCPA, which mandate that user consent must be obtained before serving personalized ads. By serving NPAs when consent status is unknown, publishers can avoid potential legal issues.

### When to Include

1. **Consent Status Unknown**: If the user dismisses the consent prompt or if the consent status cannot be determined, this attribute ensures that non-personalized ads are served instead of personalized ads.
2. **Regulatory Compliance**: To comply with privacy regulations that require non-personalized ads to be served when user consent is not explicitly given.
3. **Fallback Mechanism**: As a fallback mechanism to ensure that ads are still served even when the consent status is unclear, preventing a complete loss of ad revenue.

### Example

Here's an example of how to include the `data-npa-on-unknown-consent` attribute in your AMP ad tags:

```html
<amp-consent layout="nodisplay" id="consent-element">
  <script type="application/json">
    {
      "consentInstanceId": "my-consent",
      "consentRequired": true,
      "promptUI": "consent-ui"
    }
  </script>
  <div id="consent-ui">
    <button on="tap:consent-element.accept">Accept</button>
    <button on="tap:consent-element.reject">Reject</button>
    <button on="tap:consent-element.dismiss">Dismiss</button>
  </div>
</amp-consent>

<amp-ad
  width="300"
  height="250"
  type="doubleclick"
  data-slot="/1234567/example"
  data-block-on-consent
  data-npa-on-unknown-consent="true">
</amp-ad>
```

In this example, the `amp-ad` tag includes the `data-npa-on-unknown-consent="true"` attribute, ensuring that non-personalized ads are served if the user's consent status is unknown.

For more detailed information, you can refer to the [Google AdMob Help](https://support.google.com/admob/answer/9598414?hl=en) and [Google AdSense Help](https://support.google.com/adsense/answer/7670312?hl=en-GB) pages.
