### ISSUE TITLE
🎨 Hide Disqus ads with CSS

### ISSUE THREAD

**Issue by chriskyfung** [chriskyfung/amp-affiliately-jekyll-theme#46]
## Description
We are using Disqus to power the comment system for our AMP-based Jekyll theme. However, Disqus is showing unwanted ads on our website that we do not have control over. We want to hide these ads with CSS.

## Steps to reproduce
1. Visit any page with Disqus comments on our website.
2. Scroll down to the comment section and observe the ads.

## Expected behavior
We expect to see only the comments and no ads.

## Actual behavior
We see ads above and below the comments.

## Possible solution
We can hide the ads iframes with CSS by using the following selector:

```css
iframe[src*="ads-iframe"] {
  display: none;
}
```

## Tasks

-   [x] Edit the CSS style sheet to hide the ads iframes with the selector above.
-   [x] Test the website on different browsers and devices to ensure the ads are hidden.
-   [x] Commit and push the changes to the GitHub repository.
