### ISSUE TITLE
🧑‍💻 Improve the Front Matter CMS settings

### ISSUE THREAD

**Issue by chriskyfung** [chriskyfung/amp-affiliately-jekyll-theme#89]
## Description
This issue is about improving the Front Matter CMS setting for our AMP-powered Jekyll site. The goal is to make the setting more user-friendly, consistent, and compatible with the AMP Affiliately Jekyll Theme.

## Tasks
- [x] Review the documentation from https://chriskyfung.github.io/amp-affiliately-jekyll-theme/front-matter-guide/
- [x] Generate the JSON data for setting the `frontMatter.taxonomy.contentTypes` based on the documentation
- [x] Test the JSON data with the Front Matter CMS for VS Code
- [ ] Update the documentation with the new JSON data and any changes or additions
- [ ] Submit a pull request with the updated setting and documentation
